Algoritmo "combinacoes"
// Disciplina   : Algoritmo
// Professor   : Gustavo Guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Pedro Luno
// Data atual  : 10/07/2025
Var
// Seção de Declarações das variáveis 
   C1, C2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para C1 := 1 ate 3 faca
        Para C2 := 1 ate 3 faca
             EscrevaL(c1, c2)
        FimPara
   FimPara

Fimalgoritmo