Algoritmo "semnome"
// Disciplina   : algoritmo
// Professor   : Gustavo Guanabara
// Descrição   : comprimenta seu nome
// Autor(a)    : Pedro Luno
// Data atual  : 07/06/2025
Var
// Seção de Declarações das variáveis 
   Nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Qual seu nome? ")
   Leia(Nome)
   Escreval("Muito prazer ", nome, "!")

Fimalgoritmo