Algoritmo "semnome"
// Disciplina   : Algoritimos
// Professor   : Gustavo Guanabara
// Descrição   : Ritual de purificação, para se livrar da maldição.
// Autor(a)    : Pedro
// Data atual  : 06/06/2025
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Olá, mundo!")
   Escreva("Ritual concluido, me livrei da maldição")

Fimalgoritmo